### ISSUE TITLE
Filter for Item List

### ISSUE THREAD

**Issue by cbierman** [Pizza-and-Bier/lunafest-dyb-frontend#11]
Filter based on:
- Category
- Current bid amount (range)
- Donor fields?

**Comment by apizzimenti** [comment]
Do you wanna do this in the backend or in the frontend?

**Comment by cbierman** [comment]
I think I can just do this on the frontend since I'll have everything.

**Comment by apizzimenti** [comment]
👌 👌 👌

**Comment by cbierman** [comment]
closed by 64241435efaf8b08147af31e09385191095e1cbc
