### ISSUE TITLE
Error "obs.throw is not a function" (Auth service)

### ISSUE THREAD

**Issue by cbierman** [Pizza-and-Bier/lunafest-dyb-frontend#22]
I'm getting this error from the auth service for my registration email validator. I think it's because it's erroring while you type a the email ("calebierm").

I can catch this on my end and handle it, I just need the error to catch

EDIT: Forgot to add you can see this in feature/email-validator branch

**Comment by apizzimenti** [comment]
Fixed in f07d912.
