### ISSUE TITLE
Delete Item

### ISSUE THREAD

**Issue by cbierman** [Pizza-and-Bier/lunafest-dyb-frontend#30]
I think for now just a button on the edit screen will do.

**Comment by apizzimenti** [comment]
I have an idea for this.

**Comment by apizzimenti** [comment]
There is an `Item.remove()` function built into the API, implemented in 5379aed. However, if an item is deleted, it will not be reflected in users' lists of followed items. I'll close this for now, but we can reopen it later if it becomes an issue.
