### ISSUE TITLE
Issue placing bids

### ISSUE THREAD

**Issue by cbierman** [Pizza-and-Bier/lunafest-dyb-frontend#8]
Getting an "item is null" error in user.service.bid() (line 85)

![air-roar](https://user-images.githubusercontent.com/4315816/36337349-df14d2b0-1359-11e8-89b6-373dd2cd4e4d.PNG)

**Comment by apizzimenti** [comment]
I recreated this bug in the feature/place-a-bid branch, and it seemed like the reason that the `item is null` error was getting thrown is that the "array" of objects isn't actually an array, it's an object with unique keys. Unfortunately, this means we have to keep track of keys when listing out items.
